### ISSUE TITLE
Unable to POST attached file

### ISSUE THREAD

**Issue by dlevenson44** [dlevenson44/FindAPet#3]
I've added a form in React to handle file uploads after implementing PaperClip on my backend so users can upload image files and receive the following error when I submit a POST request with an attachment selected:

Paperclip::AdapterRegistry::NoHandlerError (No handler found for "C:\\fakepath\\C6AFA7BB-85EB-4632-9559-94124C075BB3.jpeg")

The docs for this gem doesn't mention needing a handler, have not been able to find resolution thus far.  This is being used with React on Rails, but the error seems to indicate the issue is with the PetsController.  I have researched but not found anything that I could try to resolve yet.

**Comment by dlevenson44** [comment]
Added methods to EditPetForm component to handle image uploading.  Decided to do PUT request instead of POST to make sure the image is being uploaded to an existing pet.

Image preview is rendering properly, but receiving below error when clicking submit button to upload:
ActionController::ParameterMissing (param is missing or the value is empty: pet):
 
app/controllers/pets_controller.rb:50:in `pet_params'
app/controllers/pets_controller.rb:33:in `update'

I checked the Pets controller and am unclear as to what would need to change in the update method at this time.
